version: '2'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.6
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_moodle
      - MARIADB_DATABASE=bitnami_moodle
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
    volumes:
      - 'idems_moodledb:/bitnami/mariadb'
  moodle:
    build:
      context: '.'
      dockerfile: Dockerfile
    environment:
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_NAME=bitnami_moodle
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'idems_moodlefs:/bitnami'
    depends_on:
      - mariadb
    labels:
      - 'traefik.http.routers.moodle.rule=Host(`moodle.localhost`)'
    user: '1001'
  maxima:
    image: mathinstitut/goemaxima:2023052400-latest
    restart: always
  rproxy:
    image: traefik:v2.10
    command: --api.insecure=true --providers.docker
    ports:
      - '80:80'
      - '8080:8080'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  idems_moodledb:
    driver: local
  idems_moodlefs:
    driver: local
